<a href="https://colab.research.google.com/github/Enock-Yegon/Introduction-to-Python/blob/main/day1wk3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercise 111: Only the Words

## Objective
Create a function that extracts all words from a string while removing leading and trailing punctuation marks.

---

## Requirements & Rules
1. **Punctuation Removal**: Strip punctuation marks from the **edges** of words.
   * Marks to remove: `,`, `.`, `?`, `-`, `'`, `’`, `!`, `:`, `;`
2. **Preserve Internal Punctuation**: Do **not** remove punctuation marks inside words (e.g., contractions like `don’t`, `isn’t`, or hyphenated words like `state-of-the-art`).
3. **Reusable Design**: Ensure the main execution code runs under `if __name__ == "__main__":` so this script can be safely imported as a module in future exercises (like Exercise 158).

---

## Example
* **Input**: `"Examples of contractions include: don’t, isn’t, and wouldn’t."`
* **Output**: `["Examples", "of", "contractions", "include", "don’t", "isn’t", "and", "wouldn’t"]`


In [22]:
def only_words(sentence):
    punctuation = ",, ., ?, -, ', ’, !, :, ;"
    raw_words = sentence.split()
    cleaned_words = []
    for word in raw_words:
        cleaned = word.strip(punctuation)
        if cleaned:
            cleaned_words.append(cleaned)
    return cleaned_words
while True:
    user_input = input("Enter a sentence: ")
    if user_input.strip() == "":
        print("\nDone!")
        break
    result = only_words(user_input)
    print(f"Extracted Words: {result}\n")


Enter a sentence: Good Morning
Extracted Words: ['Good', 'Morning']

Enter a sentence:  

Done!


In [27]:
import numpy as np
np.__version__

'2.0.2'

Creating an Array in Numpy


In [30]:
#0 dimension array
age = np.array(10)
print(age)

10


In [34]:
# 1 Dimension array
ages = np.array([10,12,11,15])
print(ages)

[10 12 11 15]


In [37]:
yob_age = np.array([[2000,26],[2002,24]]) # 2 dimension list
print(yob_age)

[[2000   26]
 [2002   24]]


In [55]:
#3 Dimension Array
cube_data = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])
print(cube_data)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [49]:
marks = [74,81,92,65,78]
marks_array = np.array(marks)
marks_array.ndim
print(f"The array formed is-->{marks_array}")

The array formed is-->[74 81 92 65 78]


In [51]:
marks_array.ndim

1

In [53]:
marks_array.shape

(5,)

In [57]:
cube_data.shape

(3, 3, 3)

In [58]:
yob_age.shape

(2, 2)