<a href="https://colab.research.google.com/github/Enock-Yegon/Introduction-to-Python/blob/main/day1wk3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercise 111: Only the Words

## Objective
Create a function that extracts all words from a string while removing leading and trailing punctuation marks.

---

## Requirements & Rules
1. **Punctuation Removal**: Strip punctuation marks from the **edges** of words.
   * Marks to remove: `,`, `.`, `?`, `-`, `'`, `’`, `!`, `:`, `;`
2. **Preserve Internal Punctuation**: Do **not** remove punctuation marks inside words (e.g., contractions like `don’t`, `isn’t`, or hyphenated words like `state-of-the-art`).
3. **Reusable Design**: Ensure the main execution code runs under `if __name__ == "__main__":` so this script can be safely imported as a module in future exercises (like Exercise 158).

---

## Example
* **Input**: `"Examples of contractions include: don’t, isn’t, and wouldn’t."`
* **Output**: `["Examples", "of", "contractions", "include", "don’t", "isn’t", "and", "wouldn’t"]`


In [ ]:
def only_words(sentence):
    punctuation = ",, ., ?, -, ', ’, !, :, ;"
    raw_words = sentence.split()
    cleaned_words = []
    for word in raw_words:
        cleaned = word.strip(punctuation)
        if cleaned:
            cleaned_words.append(cleaned)
    return cleaned_words
while True:
    user_input = input("Enter a sentence: ")
    if user_input.strip() == "":
        print("\nDone!")
        break
    result = only_words(user_input)
    print(f"Extracted Words: {result}\n")


Enter a sentence: Good Morning
Extracted Words: ['Good', 'Morning']

Enter a sentence:  

Done!


In [ ]:
import numpy as np
np.__version__

'2.0.2'

Creating an Array in Numpy


In [ ]:
#0 dimension array
age = np.array(10)
print(age)

10


In [ ]:
# 1 Dimension array
ages = np.array([10,12,11,15])
print(ages)

[10 12 11 15]


In [ ]:
yob_age = np.array([[2000,26],[2002,24]]) # 2 dimension list
print(yob_age)

[[2000   26]
 [2002   24]]


In [ ]:
#3 Dimension Array
cube_data = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])
print(cube_data)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [ ]:
marks = [74,81,92,65,78]
marks_array = np.array(marks)
marks_array.ndim
print(f"The array formed is-->{marks_array}")

The array formed is-->[74 81 92 65 78]


In [ ]:
marks_array.ndim

1

In [ ]:
marks_array.shape

(5,)

In [ ]:
cube_data.shape

(3, 3, 3)

In [ ]:
yob_age.shape

(2, 2)

In [ ]:
cube_data.size

27

In [ ]:
names = np.array(["John","Jane","Doe"])
names.dtype

dtype('<U4')

In [ ]:
#Array Data
import numpy as np
def student_records():
    records = [
        {"name": "Alice", "age": 20, "Score": 90, "grade": "A"},
        {"name": "Bob", "age": 21, "Score": 60, "grade": "B"},
        {"name": "Charlie", "age": 19, "Score": 50, "grade": "C"},
    ]

    data = np.array(records)
    print(data)
    print("\nShape:", data.shape)
    print("\nSize:", data.size)
    print("\nDimensions:", data.ndim)
    print("\nData Types:", data.dtype)
student_records()



[{'name': 'Alice', 'age': 20, 'Score': 90, 'grade': 'A'}
 {'name': 'Bob', 'age': 21, 'Score': 60, 'grade': 'B'}
 {'name': 'Charlie', 'age': 19, 'Score': 50, 'grade': 'C'}]

Shape: (3,)

Size: 3

Dimensions: 1

Data Types: object


In [ ]:
#List
def student_records():
    records = [
        {"name": "Alice", "age": 20, "Score": 90, "grade": "A"},
        {"name": "Bob", "age": 21, "Score": 60, "grade": "B"},
        {"name": "Charlie", "age": 19, "Score": 50, "grade": "C"},
    ]
    print(records)
    print("\nLength (Size):", len(records))
    print("\nData Type of Container:", type(records))
    print("\nData Type of First Element:", type(records[0]))
student_records()

[{'name': 'Alice', 'age': 20, 'Score': 90, 'grade': 'A'}, {'name': 'Bob', 'age': 21, 'Score': 60, 'grade': 'B'}, {'name': 'Charlie', 'age': 19, 'Score': 50, 'grade': 'C'}]

Length (Size): 3

Data Type of Container: <class 'list'>

Data Type of First Element: <class 'dict'>


In [ ]:
import numpy as np
a = np.arange(20)
print(a)
print("\na[15] =", a[15])
print("\na[-8:17:1] =", a[-8:17:1])
print("\na[10:] =", a[10:])


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

a[15] = 15

a[-8:17:1] = [12 13 14 15 16]

a[10:] = [10 11 12 13 14 15 16 17 18 19]


In [ ]:
import numpy as np
scores = np.array([82,75,91,68,80])
middle_three = scores[-4:4]
print("Original Scores:", scores)
print("\nMiddle Three Scores:", middle_three)

Original Scores: [82 75 91 68 80]

Middle Three Scores: [75 91 68]


In [ ]:
import numpy as np
scores = np.array([82,75,91,68,80])
middle_three = scores[1:4]
print("Original Scores:", scores)
print("\nMiddle Three Scores:", middle_three)

Original Scores: [82 75 91 68 80]

Middle Three Scores: [75 91 68]


In [ ]:
import numpy as np
scores = np.array([82,75,91,68,80])
middle_three = scores[1:-1]
print("Original Scores:", scores)
print("\nMiddle Three Scores:", middle_three)

Original Scores: [82 75 91 68 80]

Middle Three Scores: [75 91 68]


In [ ]:
import numpy as np
a = np.array([[1,2],[3,4],[5,6]])
print(a[[0,1,2]])

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
import numpy as np
a = np.array([19,40,50,60,70,80,70,60])
print(a[a>50])

[60 70 80 70 60]


In [ ]:
import numpy as np
num = np.zeros(5)
print(num)

[0. 0. 0. 0. 0.]


In [ ]:
number = np.arange(5,15)
print(number)

[ 5  6  7  8  9 10 11 12 13 14]


In [ ]:
numbers = np.arange(0,20,1)
print(numbers)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
#In NumPy, np.linspace() generates evenly spaced numbers over a specified interval.
space = np.linspace(0,100,10)
print(space)

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [ ]:
random = np.random.randint(0,100,10)
print(random)

[44 64 11 13 61 99 96 22 16 68]


In [ ]:
import numpy as np

# 10 random float numbers between 0 and 100
random_decimals = np.random.uniform(0, 100, 10)

print(random_decimals)

[44.76191829 34.17279883 25.19075059 86.81885047 75.91895041 90.77971401
 34.35945842  5.68533212 28.51636606  8.0496618 ]


In [ ]:
import numpy as np

# 10 random floats between 0 and 100 rounded to 2 decimal places
random_decimals = np.round(np.random.uniform(0, 100, 10), 2)

print(random_decimals)

[59.31  2.93 38.45 82.03 50.36 72.68 80.61 11.22 21.52 36.59]


In [ ]:
seed = np.random.seed(42)
print(seed)

None


Student Performance Data Analysis

Overview:
An array of 40 student scores was generated to analyze basic statistical distribution and structural properties using NumPy.

Array Properties Summary:
- Total Scores (Size): 40
- Data Type (dtype): float64 (floating-point numbers with single-decimal precision)
- Dimensions (ndim): 1D Array
- Shape: (40,)

Key Slices Extracted:
- First Five Student Scores: Represents the initial slice of records [index 0 to 4].
- Last Five Student Scores: Represents the trailing slice of records [index -5 to end].

Summary Note:
The array structure successfully holds continuous numerical values within a uniform 1-dimensional array container, allowing for fast analytical operations and slice extraction.

In [ ]:
import numpy as np

# 1. Lock seed for reproducible scores and generate 40 scores between 40.0 and 100.0
#np.random.seed(42)
scores = np.random.randint(40, 101, 40)

print(f"\nALL STUDENT SCORES = {scores}")
print(f"\nTotal number of scores (Size): {scores.size}")
print(f"\nData type (dtype): {scores.dtype}")
print(f"\nDimensions (ndim): {scores.ndim}")
print(f"\nShape: {scores.shape}")
print(f"\nFirst five scores: {scores[:5]}")
print(f"\nLast five scores:  {scores[-5:]}")


ALL STUDENT SCORES = [65 87 96 91 99 88 41 40 87 51 44 76 71 98 94 48 80 74 58 87 55 42 59 63
 93 95 72 63 91 50 88 47 75 77 79 59 74 87 64 74]

Total number of scores (Size): 40

Data type (dtype): int64

Dimensions (ndim): 1

Shape: (40,)

First five scores: [65 87 96 91 99]

Last five scores:  [59 74 87 64 74]
