<a href="https://colab.research.google.com/github/Enock-Yegon/Introduction-to-Python/blob/main/taskday5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import pandas as pd
sales = np.array([4374, 2060, 2494, 2330, 2295, 4292, 2838, 3369, 1666, 2438, 1530,
                  2682, 8500, 4371, 4119, 1330, 2885, 1969, 3591, 2715, 4053, 3633,
                  2415, 2155, 3524, 9200, 1659, 1221, 3500, 1947])
days = np.arange(1, len(sales) + 1)
df_sales = pd.DataFrame({'Day': days, 'Revenue': sales})
total_revenue = df_sales['Revenue'].sum()
mean_revenue = df_sales['Revenue'].mean()
median_revenue = df_sales['Revenue'].median()
std_revenue = df_sales['Revenue'].std()
Q1 = df_sales['Revenue'].quantile(0.25)
Q3 = df_sales['Revenue'].quantile(0.75)
IQR = Q3 - Q1
upper_bound = Q3 + (1.5 * IQR)

peak_days = df_sales[df_sales['Revenue'] > Q3]
slow_days = df_sales[df_sales['Revenue'] < Q1]

df_sales['Is_Outlier'] = df_sales['Revenue'] > upper_bound
outliers = df_sales[df_sales['Is_Outlier']]

print("\n==Sales Trends==")
print(f"Total Revenue:      KES {total_revenue:,.2f}")
print(f"Average Revenue:    KES {mean_revenue:,.2f}")
print(f"Median Revenue:     KES {median_revenue:,.2f}")
print(f"Standard Deviation: KES {std_revenue:,.2f}")

print("\n==Best performing days==")
print(f"{peak_days.to_string(index=False)}")
print(f"\nTotal Slow Days: {len(slow_days)} out of 30 days")
print(slow_days.head(10).to_string(index=False))

print("\n==Outlier Analysis==")
print(f"Q1 (25th Percentile): KES {Q1:,.2f}")
print(f"Q3 (75th Percentile): KES {Q3:,.2f}")
print(f"IQR Upper Bound:  KES {upper_bound:,.2f}")
print("\nOutlier Days:")
print(outliers[['Day', 'Revenue']].to_string(index=False))




==Sales Trends==
Total Revenue:      KES 95,155.00
Average Revenue:    KES 3,171.83
Median Revenue:     KES 2,698.50
Standard Deviation: KES 1,805.70

==Best performing days==
 Day  Revenue
   1     4374
   6     4292
  13     8500
  14     4371
  15     4119
  21     4053
  22     3633
  26     9200

Total Slow Days: 8 out of 30 days
 Day  Revenue
   2     2060
   9     1666
  11     1530
  16     1330
  18     1969
  27     1659
  28     1221
  30     1947

==Outlier Analysis==
Q1 (25th Percentile): KES 2,083.75
Q3 (75th Percentile): KES 3,622.50
IQR Upper Bound:  KES 5,930.62

Outlier Days:
 Day  Revenue
  13     8500
  26     9200


In [5]:
eye = np.eye(2)[0,1]
print(eye)


0.0


In [23]:
import numpy as np

numbers = np.arange(24)
print(numbers)
numbers = numbers.reshape(3,-1)
print(f"\n{numbers}")

maximum = np.max(numbers)
minimum = np.min(numbers)
mean = np.mean(numbers)
sum = np.sum(numbers)
standard_deviation = np.std(numbers)
medium = np.median(numbers)

print(f"\nThe maximum value is {maximum}")
print(f"The minimum value is {minimum}")
print(f"The mean value is {mean}")
print(f"The mediam value is {medium}")
print(f"The sum value is {sum}")
print(f"The standard deviation value is {standard_deviation}")




[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]

The maximum value is 23
The minimum value is 0
The mean value is 11.5
The mediam value is 11.5
The sum value is 276
The standard deviation value is 6.922186552431729


In [28]:
numbers_flattened = numbers.flatten()
print(numbers_flattened)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [34]:
numbers_3D = np.array([[[0,1],[2,3]],[[4,5],[6,7]],[[8,9],[10,11]],[[12,13],[14,15]],[[16,17],[18,19]]])
print(numbers_3D)


[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]]


In [39]:
ndim1 = numbers_3D.ndim
shape1 = numbers_3D.shape
size1 = numbers_3D.size
dtype1 = numbers_3D.dtype
print (f"ndim: {ndim1}")
print (f"shape: {shape1}")
print (f"size: {size1}")
print (f"dtype: {dtype1}")

ndim: 3
shape: (5, 2, 2)
size: 20
dtype: int64


In [51]:
heroes_data = [
    ("Queen Dania",        "Leaf",  "Nairobi", 92,8,2, "S"),
    ("Princess Arrowroot", "Root",  "Tokyo",   85,7,3, "A"),
    ("Niniya Spinach",     "Leaf",  "Tokyo",   78,6,4, "B"),
    ("King Tomato",        "Fruit", "Nairobi", 88,9,1, "S"),
    ("Samurai Kale",       "Leaf",  "Osaka",   73,5,5, "B"),
    ("Star Cabbage",       "Leaf",  "Nairobi", 65,3,7, "C"),
    ("Prince Robusta",     "Bean",  "Tokyo",   81,4,6, "A"),
    ("Night Arabica",      "Bean",  "Nairobi", 69,2,8, "C"),
]
dtype = [
    ("hero",   "U20"),
    ("team",   "U10"),
    ("city",   "U12"),
    ("power",  "i4"),
    ("wins",   "i4"),
    ("losses", "i4"),
    ("rank",   "U2"),
]
heroes = np.array(heroes_data, dtype=dtype)
heroes


array([('Queen Dania', 'Leaf', 'Nairobi', 92, 8, 2, 'S'),
       ('Princess Arrowroot', 'Root', 'Tokyo', 85, 7, 3, 'A'),
       ('Niniya Spinach', 'Leaf', 'Tokyo', 78, 6, 4, 'B'),
       ('King Tomato', 'Fruit', 'Nairobi', 88, 9, 1, 'S'),
       ('Samurai Kale', 'Leaf', 'Osaka', 73, 5, 5, 'B'),
       ('Star Cabbage', 'Leaf', 'Nairobi', 65, 3, 7, 'C'),
       ('Prince Robusta', 'Bean', 'Tokyo', 81, 4, 6, 'A'),
       ('Night Arabica', 'Bean', 'Nairobi', 69, 2, 8, 'C')],
      dtype=[('hero', '<U20'), ('team', '<U10'), ('city', '<U12'), ('power', '<i4'), ('wins', '<i4'), ('losses', '<i4'), ('rank', '<U2')])

In [46]:
print(heroes.dtype.names)

('hero', 'team', 'city', 'power', 'wins', 'losses', 'rank')


In [48]:
heroes[heroes["city"] == "Nairobi"]

array([('Queen Dania', 'Leaf', 'Nairobi', 92, 8, 2, 'S'),
       ('King Tomato', 'Fruit', 'Nairobi', 88, 9, 1, 'S'),
       ('Star Cabbage', 'Leaf', 'Nairobi', 65, 3, 7, 'C'),
       ('Night Arabica', 'Bean', 'Nairobi', 69, 2, 8, 'C')],
      dtype=[('hero', '<U20'), ('team', '<U10'), ('city', '<U12'), ('power', '<i4'), ('wins', '<i4'), ('losses', '<i4'), ('rank', '<U2')])

In [52]:
heroes[heroes["team"] == "Leaf"]

array([('Queen Dania', 'Leaf', 'Nairobi', 92, 8, 2, 'S'),
       ('Niniya Spinach', 'Leaf', 'Tokyo', 78, 6, 4, 'B'),
       ('Samurai Kale', 'Leaf', 'Osaka', 73, 5, 5, 'B'),
       ('Star Cabbage', 'Leaf', 'Nairobi', 65, 3, 7, 'C')],
      dtype=[('hero', '<U20'), ('team', '<U10'), ('city', '<U12'), ('power', '<i4'), ('wins', '<i4'), ('losses', '<i4'), ('rank', '<U2')])

In [53]:
print(np.sum(heroes['power']>=80))

4
